DICTIONARY = dictionary.txt
INPUT      = sample_input.txt
OUTPUT3    = output3.txt
OUTPUT5    = output5.txt

default:
	python assignment1.py -d $(DICTIONARY) -i $(INPUT) -o $(OUTPUT3) $(OUTPUT5)

clean:
	rm $(OUTPUT3) $(OUTPUT5)
